### ISSUE TITLE
CSS 水平垂直居中方式

### ISSUE THREAD

**Issue by theydy** [theydy/NoteBook#5]
#### 方式一：absolute 已知宽高

```css
.wrapper {
  position: relative;
}
.content {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 100px;
  height: 100px;
  margin-top: -50px;
  margin-left: -50px;
}
```

#### 方式二：absolute 未知宽高

```css
.wrapper {
  position: relative;
}
.content {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  margin: auto;
}
```

#### 方式三：transform 未知宽高

```css
.wrapper {
  position: relative;
}
.content {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```

#### 方式四：flex 未知宽高

```css
.wrapper {
  display: flex;
  justify-content: center;
  align-items: center;
}
.content {
}
```
#### 方式五：table-cell 未知宽高

```css
.wrapper {
  display: table;
  text-align: center;
}
.content {
  display: table-cell;
  vertical-align: middle;
}
```

#### 方式六：grid 已知宽高

```css
.wrapper {
  display: grid;
  grid-template-columns: 100px;
  grid-template-rows: 100px;
  justify-content: center;
  align-content: center;
  grid-template-areas: 'content';
}
.content {
  grid-area: content;
}
```
